# Generated by Django 3.1.1 on 2020-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201107_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.CharField(choices=[('Sec 1', 'Sec 1'), ('Sec 2', 'Sec 2'), ('Sec 3', 'Sec 3'), ('Sec 4', 'Sec 4'), ('J1', 'J1'), ('J2', 'J2'), ('Public', 'Public'), ('Teacher', 'Teacher')], default='Public', max_length=100),
        ),
    ]
