# Generated by Django 3.1.1 on 2020-10-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decks',
            options={},
        ),
        migrations.RemoveField(
            model_name='decks',
            name='answerImage',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='questionImage',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='questions',
        ),
        migrations.CreateModel(
            name='CardsQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=250)),
                ('questionImage', models.ImageField(upload_to='')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cards.decks')),
            ],
        ),
        migrations.CreateModel(
            name='CardsAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerText', models.CharField(max_length=250)),
                ('answerImage', models.ImageField(upload_to='')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cards.decks')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cards.cardsquestions')),
            ],
        ),
    ]
