# Generated by Django 3.1.1 on 2020-10-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20201005_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='Draft', max_length=100),
        ),
    ]
