# Generated by Django 3.1.1 on 2020-10-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_deck_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cards.cardsquestion'),
        ),
    ]
