# Generated by Django 3.1.1 on 2020-10-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20201013_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsquestion',
            name='answerImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cardsquestion',
            name='answerText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsquestion',
            name='questionText',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='CardsAnswer',
        ),
    ]
