# Generated by Django 3.1.1 on 2020-11-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20201101_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsscore',
            name='num_of_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
