# Generated by Django 3.1.1 on 2020-11-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_cardsscore_num_of_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsscore',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='cards.cardsquestion'),
        ),
    ]
