# Generated by Django 3.1.1 on 2020-11-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20201102_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
