# Generated by Django 3.1.1 on 2020-11-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20201102_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsscore',
            name='card_accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
