# Generated by Django 3.1.1 on 2020-11-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_cardsscore_card_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
