# Generated by Django 3.1.1 on 2020-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_deckaccuracy_num_of_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckaccuracy',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
