# Generated by Django 3.1.1 on 2020-11-02 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0017_deckaccuracy_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='show_score', to='cards.deckaccuracy')),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cards.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
