# Generated by Django 3.1.1 on 2020-11-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_userdeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cards.deck'),
        ),
    ]
