# Generated by Django 3.1.1 on 2020-11-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_auto_20201102_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdeck',
            name='accuracy',
        ),
    ]
