# Generated by Django 3.1.1 on 2020-11-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_delete_userdeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='availability',
            field=models.CharField(choices=[('Student', 'student'), ('Public', 'public'), ('Teacher', 'teacher'), ('Private', 'private')], default='Private', max_length=100),
        ),
    ]
