# Generated by Django 3.1.1 on 2020-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_deck_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='availability',
            field=models.CharField(choices=[('Private', 'Private'), ('Sec 1', 'sec_1'), ('Sec 2', 'sec_2'), ('Sec 3', 'sec_3'), ('Sec 4', 'sec_4'), ('J1', 'j1'), ('J2', 'j2'), ('Public', 'public'), ('Teacher', 'teacher')], default='Private', max_length=100),
        ),
    ]
