# Generated by Django 3.1.1 on 2020-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_auto_20201107_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsquestion',
            name='questionImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
